import { Metadata } from "next";
import { AuthProvider, useAuth } from "@/lib/auth";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.min.css";
import "@/app/globals.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "USC Club Matcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <ToastContainer bodyClassName="toastBody" />
          <Analytics />
        </AuthProvider>
      </body>
    </html>
  );
}
