import "@/app/globals.css";
import { QuizContextProvider } from "@/context/QuizContext";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register | USC Club Matcher",
  description: "Generated by create next app",
};

export default function NestedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <QuizContextProvider>{children}</QuizContextProvider>;
}
