import "@/app/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login | USC Club Matcher",
  description: "Generated by create next app",
};

export default function NestedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
